version: '3.7'
services:
  #db service, mysql on port 3307
  db:
    image: mysql
    container_name: studyportaldb
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_DATABASE: processed
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/data:/var/lib/mysql
  #check Dockerfile for details. studyportal default
  studyportal:
    build: .
    container_name: studyportal
    environment:
      DB_URL: jdbc:mysql://studyportaldb/processed?rewriteBatchedStatements=true&serverTimezone=Europe/Berlin
    depends_on:
      - db
    ports:
      - 8080:80
  adminer:
    image: adminer
    ports:
      - 8090:8080
volumes:
  db_data:
