version: '3.7'
services:
  db:
    #build: ./db/
    image: mysql
    container_name: myDb
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_DATABASE: processed
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/data:/var/lib/mysql
  studyportal:
    build: .
    container_name: studyportal
    environment:
      DB_URL: jdbc:mysql://myDb:3306/processed?rewriteBatchedStatements=true&serverTimezone=Europe/Berlin
    depends_on:
      - db
    ports:
      - 80:80
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db_data:
